- name: Install NGINX
  hosts: nginx
  become: yes
  roles:
    - geerlingguy.nginx

- name: Install Apache
  hosts: apache
  become: yes
  roles:
    - role: geerlingguy.apache
      vars:
        apache_listen_port: 8080
