- name: Install NGINX on nginx group
  hosts: nginx
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure NGINX is running
      service:
        name: nginx
        state: started
        enabled: yes

- name: Install Apache on apache group
  hosts: apache
  become: yes
  tasks:
    - name: Install Apache (httpd)
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes
